version: '3.8'

services:
    qdrant:
        image: qdrant/qdrant:latest
        ports:
            - 6333:6333
            - 6334:6334
        networks:
            - ragapp-network

    ragapp:
        build: ../../src/ragapp
        image: ragapp/ragapp:latest
        ports:
            - '8000:8000'
        volumes:
            - ./config:/app/config
            - ./data:/app/data
        environment:
            - VECTOR_STORE_PROVIDER=qdrant
            - QDRANT_URL=http://qdrant:6333
            - QDRANT_COLLECTION=default
            - QDRANT_API_KEY=""
            - MODEL_PROVIDER=openai
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
            - EMBEDDING_MODEL=text-embedding-ada-002
            - EMBEDDING_DIM=1536
            - MODEL=${MODEL:-gpt-4-turbo}
            - TRACKING_SCRIPT=${TRACKING_SCRIPT:-}
        depends_on:
            - qdrant
        networks:
            - ragapp-network

networks:
    ragapp-network:
        name: ragapp-network
        external: true
